
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://habacucfm.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-73386551-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "habacucfm"
title: "habacucfm"
description: "HFM plant ecology research"
keywords: "habacucfm, functional traits, habacuc flores-moreno"
favicon: "/img/blacktree.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/whitetree.ico"

background-img: "../img/front_img_one.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Plant ecology, plant functional traits, demographic processes"
  - text: "Plant functional ecology"

me-img: "/img/me.jpg"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Research #
########

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

#disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/me_umn.jpg"
    date: "June 2014 - Present"
    description: "Postdoc at the [Reich](https://www.forestry.umn.edu/people/peter-b-reich), [Borer](http://www.tc.umn.edu/~borer/Site/Welcome.html) and [Seabloom](http://www.tc.umn.edu/~seabloom/index.html) groups at UMN"
  - image: "/img/timeline/me_unsw.jpg"
    date: "February 2010 - April 2014"
    description: "PhD at [Angela Moles' Big Ecology lab](http://www.bigecology.net.au/) "
  - image: "/img/timeline/me_unam.jpg"
    date: "2003-2009"
    description: "BSc and MSc at [Meli Mandujano's research group](http://web.ecologia.unam.mx/personal/personal_perfil.php?var1=Dra.&var2=Mar%C3%ADa_del_Carmen&var3=Mandujano&var4=S%C3%A1nchez)"

# First image of the Timeline

timeline-img: "/img/timeline/start.jpg"

###########
# Contact #
###########

email: "hfloresm@umn.edu"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/habafm"
  - title: "github"
    url: "https://github.com/habacucfm"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Research: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
